import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
import joblib

spam_messages = [
    "Get rich quick!",
    "Claim your prize now!",
    "Special offer - Limited time!",
    "Congratulations, you've won!",
    "Check out this amazing deal!",
    "Urgent: Immediate action required.",
    "Meet singles in your area!",
    "Hot stock tip - guaranteed profits!",
    "Lose weight fast with this miracle product!",
    "Earn money from home!",
    "The IRS is searching for you!",
    "Amazing investment opportunity! Earn 1000% returns in just one week!",
    "Lose 20 pounds in 10 days with our magical weight loss formula!",
    "Double your money with our exclusive investment strategy.",
    "Cheap prescription medications! Viagra, Cialis, and more at unbeatable prices!",
    "You've won a luxury cruise! Claim your free vacation now!",
    "Meet hot singles in your area. Join our dating site for free!",
    "Get rich quick! Discover the secret to financial success.",
    "Enlarge your anatomy naturally with our revolutionary product!",
    "Limited-time offer: Discounted prices on designer watches!",
    "Work from home and make $5000 per week guaranteed!",
    "Hot stock picks! Invest in the next big thing now!",
    "Unlock the secret to financial freedom. Join our exclusive program.",
    "Exclusive online deals! Save big on electronics, fashion, and more!",
    "Win a dream vacation! Enter our contest now.",
    "Eliminate debt with our proven debt reduction plan!",
    "Boost your credit score instantly with our credit repair services.",
    "Discover the secret to success with our life-changing courses!",
    "Guaranteed weight loss in 7 days. Try our new diet plan!",
    "Unlock the power of your mind with our meditation techniques.",
    "Incredible investment opportunity! Don't miss out on huge profits!",
    "Your bank account needs attention. Click to verify your details.",
    "Urgent: You've won a $1000 gift card. Claim it now!",
    "Earn passive income with our automated money-making system.",
    "Special discount on luxury handbags. Limited stock available!",
    "Congratulations! You're our 1 millionth visitor. Claim your prize!",
    "Get a degree in days. No exams, no classes. Instant diploma!",
    "Your package is waiting. Click to track and claim it.",
    "Increase your online presence with our social media marketing services.",
    "Free trial for the latest anti-aging cream. Look 10 years younger!",
    "Exciting job opportunities. Work from home and earn big.",
    "Exclusive access to government grants. Apply now!",
    "Need a loan? Get approved instantly with our quick loan services.",
    "Your credit card has been charged. Click to dispute the transaction.",
    "Limited-time offer: Win a brand new car! Enter our sweepstakes.",
    "Guaranteed income for life. Join our retirement plan now!",
    "Double your internet speed with our high-speed internet service.",
    "Limited stock: Buy one, get one free on all electronics!",
    "Congratulations! You've been selected for a free trial of our software.",
    "Unlock the secrets of the universe with our psychic readings.",
    "Earn $100 per hour from home. No experience required!",
    "Exclusive offer: Make $5000 per week working from home!",
    "Limited-time discount on luxury vacations. Book now and save!",
    "Hot stock alert! Invest in the next big tech company.",
    "Double your income with our proven financial strategy.",
    "Unlock the secret to youthful skin with our anti-aging serum.",
    "You've won a shopping spree! Claim your $1000 gift card.",
    "Incredible investment opportunity! Join our elite investment club.",
    "Special discount on premium watches. Limited stock available!",
    "Congratulations! You've qualified for a free laptop. Claim it now!",
    "Boost your energy and lose weight with our miracle supplement.",
    "Exclusive online deals! Save up to 70% on top brands.",
    "Limited-time offer: Win a luxury car. Enter our sweepstakes!",
    "Eliminate credit card debt with our debt consolidation program.",
    "Get a degree in your chosen field. No exams, instant diploma!",
    "Urgent: Your bank account needs attention. Click to verify.",
    "Earn passive income with our automated affiliate program.",
    "Limited stock: Buy one, get one free on all electronics!",
    "Congratulations! You've been selected for a dream vacation.",
    "Unlock the power of manifestation. Join our life-changing course.",
    "Limited slots available for our exclusive investment webinar.",
    "Instant loan approval. Get cash in your account today!",
    "Win big with our online casino. Claim your free spins now!",
    "Exciting job opportunities. Work from home and earn big.",
    "Limited-time discount on designer handbags. Shop now!",
    "Guaranteed income for life. Join our retirement plan now!",
    "Double your internet speed with our high-speed internet service.",
    "Limited stock: Get the latest gadgets at unbeatable prices!",
    "Congratulations! You've won a year's supply of premium coffee.",
    "Boost your credit score with our credit repair services.",
    "Limited-time offer: Win a brand new motorcycle. Enter now!",
    "Increase your online presence with our social media services.",
    "Lose 10 pounds in 5 days with our revolutionary diet plan.",
    "Your package is waiting. Click to track and claim it.",
    "Special discount on top-rated laptops. Don't miss out!",
    "Guaranteed weight loss in 7 days. Try our detox tea now!",
    "Your credit card has been charged. Click to dispute the transaction.",
    "Win a year's supply of premium skincare products. Enter today!",
    "Unlock the secrets of the universe with our astrology readings.",
    "Limited stock: Buy one, get one free on all fashion items!",
    "Share your credit card number",
    "Share your OTP",
    "Your account is blocked share your OTP as soon as possible",
    "Hurray you won trip to Hawaii",
    "You won trip",
]

legitimate_messages = [
    "Your report deadline is near",
    "credited from youur bank account",
    "This is a legitimate message.",
    "Another non-spam message.",
    "Important information about your account.",
    "Your bank account",
    " has been successfully withdrawn from your bank account"
    "Thank you for your purchase.",
    "Your appointment is confirmed.",
    "Reminder: Meeting at 3 PM.",
    "Invoice payment received.",
    "Updates on your subscription.",
    "Weather forecast for the weekend.",
    "Happy birthday! Enjoy your special day.",
    "Don't share your personal details.",
    "Weekly team brainstorming session on Wednesday. Bring your ideas!",
    "Reminder: Submit your travel expenses by the end of the month.",
    "Family movie night at my place on Saturday. What's your favorite genre?",
    "Important client meeting tomorrow at 2 pm. Prepare your presentation.",
    "Project update meeting moved to Friday at 11 am. Mark your calendars!",
    "Dinner reservation for four at the Italian restaurant on Sunday. Excited!",
    "Invoice for recent project work attached. Please review and confirm.",
    "Your online order has been shipped. Track your package here.",
    "Confirmation of hotel reservation for your upcoming trip.",
    "Happy birthday to our team member! Let's celebrate during lunch.",
    "Client feedback form attached. Your input is highly valued.",
    "Book club meeting next week. Don't forget to finish the assigned chapters!",
    "Exciting news: Our team achieved a record-breaking sales month!",
    "Weekly team status meeting on Monday. Agenda items welcome.",
    "Coffee break tomorrow. Let's catch up on the latest projects.",
    "Reminder: Parent-teacher meeting next Tuesday. Discuss your child's progress.",
    "Lunch meeting with the marketing team on Thursday. New campaigns ahead!",
    "Invitation to the company picnic this weekend. Join the fun!",
    "Weekly progress report attached. Highlighting key achievements.",
    "Team-building activity planned for Saturday. Get ready for some fun!",
    "Update on the upcoming industry conference. Are you attending?",
    "Agenda for the board of directors meeting next month attached.",
    "Welcome to the team! Looking forward to working together.",
    "Important update: New features added to our software. Update now.",
    "Monthly performance report for your department attached.",
    "Lunch meetup on Friday. Discussing potential collaborations.",
    "Training session for the new project management tool on Tuesday.",
    "Urgent: Security update for your online account. Take action now.",
    "Coffee break tomorrow. Let's discuss the upcoming project.",
    "Announcement: Company-wide town hall meeting scheduled for next week.",
    "Meeting rescheduled to 3 pm. Please confirm your availability.",
    "Review the proposal document before our team meeting tomorrow.",
    "Friendly reminder: Submit your monthly report by Friday.",
    "Flight details for your upcoming business trip attached.",
    "Project update meeting scheduled for Thursday at 10 am.",
    "Family dinner at our place on Saturday. Looking forward to seeing you!",
    "Invoice payment confirmation for your recent purchase.",
    "Your order has been shipped. Track your package with the provided link.",
    "Confirmation of reservation for your weekend getaway.",
    "Birthday wishes from the entire team. Have a fantastic day!",
    "Important client meeting rescheduled to Monday at 2 pm.",
    "Submit your expense reports by the end of the week.",
    "Family gathering this weekend. Let us know if you can make it.",
    "Book club meeting on Thursday. Don't forget to bring your book!",
    "Review the marketing strategy for the upcoming campaign.",
    "Upcoming project deadline approaching. Check your tasks.",
    "Confirmation of flight reservation for your upcoming vacation.",
    "Weekly team status meeting on Friday at 9 am.",
    "Dinner reservation for two at your favorite restaurant on Saturday.",
    "Happy hour at the office this Friday. Join us for some fun!",
    "Board meeting agenda for next week attached.",
    "Welcome to the team! Looking forward to working together.",
    "Agenda for the marketing team meeting on Wednesday.",
    "Reminder: Parent-teacher conference next Tuesday.",
    "Invitation to the company holiday party. Save the date!",
    "Important update: New features added to our software.",
    "Monthly performance report attached. Take a look.",
    "Lunch meeting with the client on Thursday at noon.",
    "Agenda for the quarterly review meeting on Monday.",
    "Your feedback is important. Please complete our survey.",
    "Save the date: Company retreat planned for next month.",
    "New product launch event on Friday. Be sure to attend!",
    "Team-building activity on Saturday. Get ready for some fun!",
    "Annual company picnic this weekend. Bring your family!",
    "Coffee meetup to discuss the upcoming project. Are you available?",
    "Exciting news! Our team won the innovation award.",
    "Update on the upcoming conference. Review the agenda.",
    "Employee of the month announcement. Congrats to the winner!",
    "Thank you for your purchase. Your order details are attached.",
    "Training session for the new software on Thursday. Be there!",
    "Announcement: Company-wide town hall meeting next week.",
    "Urgent: Security update for your online account. Take action now.",
    "Team outing to the new escape room on Friday. Join us!",
    "Agenda for the board of directors meeting attached.",
    "Quarterly financial report for your review. Check the numbers.",
    "Product demo scheduled for Monday. Don't miss it!",
    "Reminder: Employee benefits enrollment period ends this week.",
    "Coffee break tomorrow. Let's catch up over a cup of coffee!",
    "Your subscription renewal is due soon. Renew now to avoid interruptions.",
    "A new sign-in on ",
]

# Combine spam and legitimate messages
all_messages = spam_messages + legitimate_messages
all_labels = [1] * len(spam_messages) + [0] * len(legitimate_messages)

# Shuffle the combined messages and labels
df = pd.DataFrame({'message': all_messages, 'label': all_labels})
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

# Train the model
try:
    X_train, X_test, y_train, y_test = train_test_split(df['message'], df['label'], test_size=0.2, random_state=42)

    vectorizer = CountVectorizer()
    X_train_vectorized = vectorizer.fit_transform(X_train)

    classifier = MultinomialNB()
    classifier.fit(X_train_vectorized, y_train)

    # Save the trained model and vectorizer
    joblib.dump(classifier, 'classifier_model.joblib')
    joblib.dump(vectorizer, 'vectorizer.joblib')
    print("Model trained and saved successfully.")
except Exception as e:
    print("An error occurred during training: {}".format(str(e)))
